# Generated by Django 3.2.3 on 2021-05-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental_app.file'),
        ),
    ]
